/*
 * generated by Xtext 2.12.0
 */
package org.pkt.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.pkt.parser.antlr.internal.InternalTymParser;
import org.pkt.services.TymGrammarAccess;

public class TymParser extends AbstractAntlrParser {

	@Inject
	private TymGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTymParser createParser(XtextTokenStream stream) {
		return new InternalTymParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TymGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TymGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
