/*
 * generated by Xtext 2.12.0
 */
package org.pkt.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.pkt.TymRuntimeModule
import org.pkt.TymStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TymIdeSetup extends TymStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TymRuntimeModule, new TymIdeModule))
	}
	
}
