/**
 * generated by Xtext 2.12.0
 */
package org.pkt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.pkt.ui.AbstractTymUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TymUiModule extends AbstractTymUiModule {
  public TymUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
