/*
 * generated by Xtext 2.12.0
 */
package org.pkt.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.pkt.Tym.ui.internal.TymActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TymExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TymActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TymActivator.getInstance().getInjector(TymActivator.ORG_PKT_TYM);
	}
	
}
