/**
 * generated by Xtext 2.12.0
 */
package org.pkt.tym;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.pkt.tym.TymPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
