/**
 * generated by Xtext 2.12.0
 */
package org.pkt.tym;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.pkt.tym.FunctionCall#getFuncname <em>Funcname</em>}</li>
 *   <li>{@link org.pkt.tym.FunctionCall#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.pkt.tym.TymPackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Funcname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Funcname</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Funcname</em>' reference.
   * @see #setFuncname(Function)
   * @see org.pkt.tym.TymPackage#getFunctionCall_Funcname()
   * @model
   * @generated
   */
  Function getFuncname();

  /**
   * Sets the value of the '{@link org.pkt.tym.FunctionCall#getFuncname <em>Funcname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Funcname</em>' reference.
   * @see #getFuncname()
   * @generated
   */
  void setFuncname(Function value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.pkt.tym.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.pkt.tym.TymPackage#getFunctionCall_Params()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getParams();

} // FunctionCall
