/*
 * generated by Xtext 2.12.0
 */
package org.pkt.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTymScopeProvider extends DelegatingScopeProvider {
}
