/*
 * generated by Xtext 2.12.0
 */
package org.pkt.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.pkt.Tym.ui.internal.TymActivator;

public class TymUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TymActivator.getInstance().getInjector("org.pkt.Tym");
	}

}
