/**
 * generated by Xtext 2.12.0
 */
package org.pkt.validation;

import org.pkt.validation.AbstractTymValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TymValidator extends AbstractTymValidator {
}
