/**
 * generated by Xtext 2.12.0
 */
package org.pkt;

import org.pkt.TymStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TymStandaloneSetup extends TymStandaloneSetupGenerated {
  public static void doSetup() {
    new TymStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
