/**
 * generated by Xtext 2.12.0
 */
package org.pkt.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.pkt.TymRuntimeModule;
import org.pkt.TymStandaloneSetup;
import org.pkt.ide.TymIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TymIdeSetup extends TymStandaloneSetup {
  @Override
  public Injector createInjector() {
    TymRuntimeModule _tymRuntimeModule = new TymRuntimeModule();
    TymIdeModule _tymIdeModule = new TymIdeModule();
    return Guice.createInjector(Modules2.mixin(_tymRuntimeModule, _tymIdeModule));
  }
}
