/**
 * generated by Xtext 2.12.0
 */
package org.pkt.ide;

import org.pkt.ide.AbstractTymIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TymIdeModule extends AbstractTymIdeModule {
}
